### ISSUE TITLE
exocom: security - notify message is unauthorized

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exocom#266]
On unauthorized message, send a message with name "message unauthorized" on the same activity id with the unauthorized message as the payload. Otherwise the message sender never gets an notice that there was message was unauthorized.

#### Expected Workflow
* test-service sends message A with activityId 123
* security service determines message A is unauthorized
* exocom should send a message "message unauthorized" with activity 123 and A is the payload
  * currently exocom only logs this and does not send a message. 

@kevgo @alexdavid @hugobho thoughts?

**Comment by kevgo** [comment]
We have several courses of action here:
1. tell the sending service that the message is unauthorized. This behavior makes sense if the error is fixable by the sender, with the expectation that the sender sends the message again in a better way that will be authorized. 
2. log the security violation and shut down the service that tries to send unauthorized messages. This behavior makes sense if we assume the error is not fixable by the sender but a bug in the application, or the result of the service being hacked.
3. crash the entire application. This behavior makes sense in dev mode, so that the developer sees what the problem is, together with stack traces.

I think (3) makes the most sense in development mode, and (2) makes the most sense in production. If we do (1), then we must add logic to every service to handle "unauthorized" messages. I have a hard time imagining any service-specific logic here.

**Comment by charlierudolph** [comment]
In regard to `1)` I'm not necessarily expecting the user to do anything with it. I just like the idea of having a message returned so it doesn't have to timeout when we know no message will be returned. The reply handler could see the message name wasn't the one expected. If it was a restful endpoint, it could return a 401 instead of a 500 if it sees the message name "message unauthorized".

In regards to `2)` I don't know if its worth shutting down the service as it may still be sending other legitimate messages.

With regard to `3)`, I think just printing out an impossible to miss error message might be better so it doesn't break down the flow of development.

**Comment by kevgo** [comment]
You are right, an `unauthorized` message makes sense if we consider unauthorized messages a legitimate part of business logic. For example, if the currently logged in user doesn't have the privileges to do a certain activity, resulting in an `unauthorized` event. It should not crash anything but return a nice 401 error, since crashing opens the chance for DOS attacks.
